# Quiz 1 - 21 de agosto de 2019

## Nombre:

Se tiene una base de datos de evaluación de automóviles, en donde cada automovil se ha caracterizado mediante 6 atributos:  

1. La precio de compra, llamado *buying* , que puede tener los siguientes valores: vhigh, high, med, low. 
2. El costo del mantenimiento, llamado *maint* que puede tener los siguientes valores: vhigh, high, med, low. 
3. El número de puertas, llamado *doors*, que puede tener los siguientes valores: 2, 3, 4, 5more. 
4. La capacidad experesada en el número de personas, llamado *persons*, que puede tener los siguientes valores: 2, 4, more. 
5. El tamaño del portamaletas,llamado *lug_boot*, que puede tener los siguientes valores: small, med, big. 
6. La seguridad estimada del auto, llamado *safety*,que puede tener los siguientes valores: low, med, high. 

De acuerdo con estas seis características, el auto puede ser clasificado en inaceptable (*unacc*), aceptable (*acc*), bueno (*good*) o muy bueno (*vgood*).

Le piden construir un sistema experto que clasifique automáticamente los autores utilizando la base de datos mencionada para su entrenamiento y validación, y el modelo de regresión logística como algoritmo de aprendizaje de máquina. Para la construcción del sistema tenga en cuenta las siguientes condiciones:

1. La base de datos y su descripción se encuentra el la página https://archive.ics.uci.edu/ml/datasets/Car+Evaluation. Debe descargar los datos y separarlos de las etiquetas de forma correcta. 
2. El algoritmo de regresión logística no acepta variables categóricas como entradas o salidas (letras), por tanto debe convertir las variables que tiene a valores numéricos (variables numéricas). La forma en se haga la conversión es libre, pero debe ser especificada en los comentarios del código. Recuerde que debe hacer esto tanto para los datos como para las etiquetas.
3. Se debe tener una etapa de preprocesamiento.
4. Se debe mostrar el acierto de clasificación.
5. Si requiere alguna información que no está especificada en las condiciones, la debe suponer y justificar correctamente.

In [80]:
#espacio para solucionar el quiz 1
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from numpy import genfromtxt

data = genfromtxt('car.txt', delimiter=',',dtype=str)


X,y = data[:,:-1],data[:,-1]

## Procedo a convertir en valores numericos cada caracteristicas
#creo un diccionario con claves que tienen un valor el cual lo asignaré despues.
buying = {'vhigh': 0,'high': 1,'med':2,'low':3}
maint = {'vhigh': 0,'high': 1,'med':2,'low':3}
doors = {'2':0,'3':1,'3':2,'4':3,'5more':4}
persons ={'2':0,'4':1,'more':2}
lug_boot = {'small':0,'med':1,'big':2}
safety = {'low':0,'med':1,'high':2}
caracteristica = {'unacc':0,'acc':1,'good':2,'vgood':2}


a = len(y)
for x in range(a):
    y[x] = caracteristica.get(y[x])#asigno, de acuerdo a una llave, su respectivo valor
    

b = len(X)

corrCarac = X[:,1]

for x in range(a):
    #asigno, de acuerdo a una llave, su respectivo valor
    X[x,0] = buying.get(X[x,0])
    X[x,1] = maint.get(X[x,1])
    X[x,2] = doors.get(X[x,2])
    X[x,3] = persons.get(X[x,3])
    X[x,4] = lug_boot.get(X[x,4])
    X[x,5] = safety.get(X[x,5])

X = X.astype(np.float)
y = y.astype(np.int64)
print(y)
print(X)

#particiono los datos 80 y 20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)
print(X_train.shape, X_test.shape)

#proceso a hacer la etapa de preprocesamiento
def remocion(X_train, X_test):
    media = X_train.mean(axis = 0)
    desviacion = X_train.std(axis = 0)
    X_train_prepro = (X_train - media)/desviacion
    X_test_prepro = (X_test - media)/desviacion
    return X_train_prepro, X_test_prepro

X_train_prepo, X_test_prepro = remocion(X_train, X_test)

#instancio el clasificador
clasificador = LogisticRegression(C = 1000.0, random_state = 0)
clasificador.fit(X_train_prepo, y_train)

#test de validación
y_pred = clasificador.predict(X_test_prepro)


error = np.mean(y_test != y_pred)
print(y_pred)
print(y_test)
print(error*100)
acierto = np.mean(y_test == y_pred)
print(acierto*100)
acc = 100.0*(y_test == y_pred).sum()/X_test_prepro.shape[0] 
print('El acierto de clasificación es del ',acc , '%')



[0 0 0 ... 0 2 2]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 2.]
 ...
 [3. 3. 4. 2. 2. 0.]
 [3. 3. 4. 2. 2. 1.]
 [3. 3. 4. 2. 2. 2.]]
(1209, 6) (519, 6)
[0 0 0 0 0 2 0 1 0 0 0 1 0 0 0 0 0 0 0 0 2 1 2 0 0 0 0 0 1 0 1 0 0 1 2 0 0
 0 0 1 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1 1
 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 2 0 0 0 0 0 0 1 0 2 1 0 1 0 0 0
 1 0 0 0 2 0 0 0 0 0 0 1 1 0 0 0 1 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0
 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
 0 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 0 2 0 1 1 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 2 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 2
 0 0 0 0 0 1 0 0 2 0 1 0 1 0 0 0 0 1 0 0 2 0 0 0 1 0 0 0 0 0 0 2 2 0 0 0 2
 0 0 0 0 0 0 2 1 0 1 2 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 1 0 0 1 0 1 0 0 2 0 0
 0 1 1

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Si requiere alguna información que no está especificada en las condiciones, la debe suponer y justificar correctamente

R/ es importante saber como debemos dividir la base de datos, por que si se tiene en cuenta la division "Estandar" que es un 70 30 nos sale mejor porcenta
